//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pogotowie_gazowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Awaria
    {
        public string Powód { get; set; }
        public System.DateTime Data { get; set; }
        public string Miejsce { get; set; }
        public int ID_Awarii { get; set; }
        public Nullable<int> ID_Pojazdu { get; set; }
        public Nullable<int> ID_Sprzetu { get; set; }
    
        public virtual Pojazd Pojazd { get; set; }
        public virtual Sprzet Sprzet { get; set; }
    }
}
