//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pogotowie_gazowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pojazd()
        {
            this.Awaria = new HashSet<Awaria>();
        }
    
        public string Marka { get; set; }
        public string Model { get; set; }
        public System.DateTime Data_zakupu { get; set; }
        public int Rocznik { get; set; }
        public int ID_Pojazdu { get; set; }
        public int ID_Pracownika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Awaria> Awaria { get; set; }
        public virtual Pracownik Pracownik { get; set; }
    }
}
