//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pogotowie_gazowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprzet()
        {
            this.Awaria = new HashSet<Awaria>();
        }
    
        public int ID_Sprzetu { get; set; }
        public string Nazwa { get; set; }
        public string Czy_uszkodzony { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Awaria> Awaria { get; set; }
    }
}
